==== START logs for container kube-scheduler of pod kube-system/kube-scheduler-response-1-control-plane ====
I0109 21:49:47.791148       1 serving.go:386] Generated self-signed cert in-memory
W0109 21:49:48.020105       1 authentication.go:370] Error looking up in-cluster authentication configuration: Get "https://172.18.0.16:6443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication": dial tcp 172.18.0.16:6443: connect: connection refused
W0109 21:49:48.020137       1 authentication.go:371] Continuing without authentication configuration. This may treat all requests as anonymous.
W0109 21:49:48.020143       1 authentication.go:372] To require authentication configuration lookup to succeed, set --authentication-tolerate-lookup-failure=false
I0109 21:49:48.024169       1 server.go:167] "Starting Kubernetes Scheduler" version="v1.31.0"
I0109 21:49:48.024239       1 server.go:169] "Golang settings" GOGC="" GOMAXPROCS="" GOTRACEBACK=""
I0109 21:49:48.026434       1 configmap_cafile_content.go:205] "Starting controller" name="client-ca::kube-system::extension-apiserver-authentication::client-ca-file"
I0109 21:49:48.026459       1 shared_informer.go:313] Waiting for caches to sync for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
W0109 21:49:48.026960       1 reflector.go:561] runtime/asm_amd64.s:1695: failed to list *v1.ConfigMap: Get "https://172.18.0.16:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dextension-apiserver-authentication&limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.027024       1 reflector.go:158] "Unhandled Error" err="runtime/asm_amd64.s:1695: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get \"https://172.18.0.16:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dextension-apiserver-authentication&limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
I0109 21:49:48.027166       1 tlsconfig.go:243] "Starting DynamicServingCertificateController"
I0109 21:49:48.027214       1 secure_serving.go:213] Serving securely on 127.0.0.1:10259
W0109 21:49:48.029198       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.ReplicationController: Get "https://172.18.0.16:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
W0109 21:49:48.029250       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PersistentVolumeClaim: Get "https://172.18.0.16:6443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.029278       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.ReplicationController: failed to list *v1.ReplicationController: Get \"https://172.18.0.16:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
E0109 21:49:48.029299       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PersistentVolumeClaim: failed to list *v1.PersistentVolumeClaim: Get \"https://172.18.0.16:6443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:48.029198       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Node: Get "https://172.18.0.16:6443/api/v1/nodes?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
W0109 21:49:48.029301       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.StorageClass: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.029336       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Node: failed to list *v1.Node: Get \"https://172.18.0.16:6443/api/v1/nodes?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:48.029327       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSIStorageCapacity: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/csistoragecapacities?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
W0109 21:49:48.029394       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.ReplicaSet: Get "https://172.18.0.16:6443/apis/apps/v1/replicasets?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
W0109 21:49:48.029307       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Service: Get "https://172.18.0.16:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.029369       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.StorageClass: failed to list *v1.StorageClass: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
E0109 21:49:48.029409       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSIStorageCapacity: failed to list *v1.CSIStorageCapacity: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/csistoragecapacities?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:48.029407       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PodDisruptionBudget: Get "https://172.18.0.16:6443/apis/policy/v1/poddisruptionbudgets?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
W0109 21:49:48.029458       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.StatefulSet: Get "https://172.18.0.16:6443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.029491       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: Get \"https://172.18.0.16:6443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:48.029415       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Pod: Get "https://172.18.0.16:6443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.029491       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: Get \"https://172.18.0.16:6443/apis/policy/v1/poddisruptionbudgets?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
E0109 21:49:48.029445       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.ReplicaSet: failed to list *v1.ReplicaSet: Get \"https://172.18.0.16:6443/apis/apps/v1/replicasets?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
E0109 21:49:48.029517       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Pod: failed to list *v1.Pod: Get \"https://172.18.0.16:6443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:48.029226       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PersistentVolume: Get "https://172.18.0.16:6443/api/v1/persistentvolumes?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
W0109 21:49:48.029518       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSINode: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/csinodes?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.029445       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: Get \"https://172.18.0.16:6443/api/v1/services?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
E0109 21:49:48.029541       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PersistentVolume: failed to list *v1.PersistentVolume: Get \"https://172.18.0.16:6443/api/v1/persistentvolumes?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:48.029292       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSIDriver: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.029583       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:48.029289       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Namespace: Get "https://172.18.0.16:6443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.029598       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get \"https://172.18.0.16:6443/api/v1/namespaces?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
E0109 21:49:48.029555       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSINode: failed to list *v1.CSINode: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/csinodes?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:48.843881       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PodDisruptionBudget: Get "https://172.18.0.16:6443/apis/policy/v1/poddisruptionbudgets?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.843933       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: Get \"https://172.18.0.16:6443/apis/policy/v1/poddisruptionbudgets?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:48.873598       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Namespace: Get "https://172.18.0.16:6443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.873646       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get \"https://172.18.0.16:6443/api/v1/namespaces?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:48.964755       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Pod: Get "https://172.18.0.16:6443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.964808       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Pod: failed to list *v1.Pod: Get \"https://172.18.0.16:6443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:48.972503       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSIStorageCapacity: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/csistoragecapacities?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:48.972558       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSIStorageCapacity: failed to list *v1.CSIStorageCapacity: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/csistoragecapacities?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:49.009131       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.StorageClass: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:49.009173       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.StorageClass: failed to list *v1.StorageClass: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:49.023045       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.StatefulSet: Get "https://172.18.0.16:6443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:49.023087       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: Get \"https://172.18.0.16:6443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:49.029879       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.ReplicaSet: Get "https://172.18.0.16:6443/apis/apps/v1/replicasets?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:49.029944       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.ReplicaSet: failed to list *v1.ReplicaSet: Get \"https://172.18.0.16:6443/apis/apps/v1/replicasets?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:49.110736       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSINode: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/csinodes?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:49.110778       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSINode: failed to list *v1.CSINode: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/csinodes?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:49.226942       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PersistentVolume: Get "https://172.18.0.16:6443/api/v1/persistentvolumes?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:49.226985       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PersistentVolume: failed to list *v1.PersistentVolume: Get \"https://172.18.0.16:6443/api/v1/persistentvolumes?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:49.231481       1 reflector.go:561] runtime/asm_amd64.s:1695: failed to list *v1.ConfigMap: Get "https://172.18.0.16:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dextension-apiserver-authentication&limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:49.231520       1 reflector.go:158] "Unhandled Error" err="runtime/asm_amd64.s:1695: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get \"https://172.18.0.16:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dextension-apiserver-authentication&limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:49.445973       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSIDriver: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:49.446014       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:49.552054       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Service: Get "https://172.18.0.16:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:49.552098       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: Get \"https://172.18.0.16:6443/api/v1/services?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:49.560774       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.ReplicationController: Get "https://172.18.0.16:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:49.560821       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.ReplicationController: failed to list *v1.ReplicationController: Get \"https://172.18.0.16:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:49.570466       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Node: Get "https://172.18.0.16:6443/api/v1/nodes?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:49.570510       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Node: failed to list *v1.Node: Get \"https://172.18.0.16:6443/api/v1/nodes?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:49.612112       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PersistentVolumeClaim: Get "https://172.18.0.16:6443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:49.612156       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PersistentVolumeClaim: failed to list *v1.PersistentVolumeClaim: Get \"https://172.18.0.16:6443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:50.763320       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Namespace: Get "https://172.18.0.16:6443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:50.763364       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get \"https://172.18.0.16:6443/api/v1/namespaces?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:50.870251       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.ReplicaSet: Get "https://172.18.0.16:6443/apis/apps/v1/replicasets?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:50.870295       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.ReplicaSet: failed to list *v1.ReplicaSet: Get \"https://172.18.0.16:6443/apis/apps/v1/replicasets?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:50.989042       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.StatefulSet: Get "https://172.18.0.16:6443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:50.989086       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: Get \"https://172.18.0.16:6443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:51.108470       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PersistentVolume: Get "https://172.18.0.16:6443/api/v1/persistentvolumes?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:51.108516       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PersistentVolume: failed to list *v1.PersistentVolume: Get \"https://172.18.0.16:6443/api/v1/persistentvolumes?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:51.152567       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSINode: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/csinodes?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:51.152607       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSINode: failed to list *v1.CSINode: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/csinodes?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:51.247575       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSIStorageCapacity: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/csistoragecapacities?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:51.247641       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSIStorageCapacity: failed to list *v1.CSIStorageCapacity: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/csistoragecapacities?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:51.338560       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSIDriver: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:51.338600       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:51.520609       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Node: Get "https://172.18.0.16:6443/api/v1/nodes?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:51.520661       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Node: failed to list *v1.Node: Get \"https://172.18.0.16:6443/api/v1/nodes?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:51.579600       1 reflector.go:561] runtime/asm_amd64.s:1695: failed to list *v1.ConfigMap: Get "https://172.18.0.16:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dextension-apiserver-authentication&limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:51.579643       1 reflector.go:158] "Unhandled Error" err="runtime/asm_amd64.s:1695: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get \"https://172.18.0.16:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dextension-apiserver-authentication&limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:51.601334       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PodDisruptionBudget: Get "https://172.18.0.16:6443/apis/policy/v1/poddisruptionbudgets?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:51.601379       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: Get \"https://172.18.0.16:6443/apis/policy/v1/poddisruptionbudgets?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:51.701587       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Pod: Get "https://172.18.0.16:6443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:51.701626       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Pod: failed to list *v1.Pod: Get \"https://172.18.0.16:6443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:51.826671       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.ReplicationController: Get "https://172.18.0.16:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:51.826716       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.ReplicationController: failed to list *v1.ReplicationController: Get \"https://172.18.0.16:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:52.047583       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.StorageClass: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:52.047611       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.StorageClass: failed to list *v1.StorageClass: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:52.463443       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Service: Get "https://172.18.0.16:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:52.463499       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: Get \"https://172.18.0.16:6443/api/v1/services?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:52.778401       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PersistentVolumeClaim: Get "https://172.18.0.16:6443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:52.778457       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PersistentVolumeClaim: failed to list *v1.PersistentVolumeClaim: Get \"https://172.18.0.16:6443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:54.460939       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSINode: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/csinodes?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:54.461004       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSINode: failed to list *v1.CSINode: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/csinodes?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:54.689348       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.ReplicaSet: Get "https://172.18.0.16:6443/apis/apps/v1/replicasets?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:54.689387       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.ReplicaSet: failed to list *v1.ReplicaSet: Get \"https://172.18.0.16:6443/apis/apps/v1/replicasets?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:54.923809       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Node: Get "https://172.18.0.16:6443/api/v1/nodes?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:54.923851       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Node: failed to list *v1.Node: Get \"https://172.18.0.16:6443/api/v1/nodes?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:55.199769       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSIDriver: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:55.199812       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSIDriver: failed to list *v1.CSIDriver: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/csidrivers?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:55.625421       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Namespace: Get "https://172.18.0.16:6443/api/v1/namespaces?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:55.625463       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Namespace: failed to list *v1.Namespace: Get \"https://172.18.0.16:6443/api/v1/namespaces?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:55.749557       1 reflector.go:561] runtime/asm_amd64.s:1695: failed to list *v1.ConfigMap: Get "https://172.18.0.16:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dextension-apiserver-authentication&limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:55.749599       1 reflector.go:158] "Unhandled Error" err="runtime/asm_amd64.s:1695: Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: Get \"https://172.18.0.16:6443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dextension-apiserver-authentication&limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:55.761286       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Pod: Get "https://172.18.0.16:6443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:55.761328       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Pod: failed to list *v1.Pod: Get \"https://172.18.0.16:6443/api/v1/pods?fieldSelector=status.phase%21%3DSucceeded%2Cstatus.phase%21%3DFailed&limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:55.783012       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.ReplicationController: Get "https://172.18.0.16:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:55.783067       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.ReplicationController: failed to list *v1.ReplicationController: Get \"https://172.18.0.16:6443/api/v1/replicationcontrollers?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:55.918952       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.StatefulSet: Get "https://172.18.0.16:6443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:55.918994       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.StatefulSet: failed to list *v1.StatefulSet: Get \"https://172.18.0.16:6443/apis/apps/v1/statefulsets?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:56.338578       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PersistentVolumeClaim: Get "https://172.18.0.16:6443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:56.338628       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PersistentVolumeClaim: failed to list *v1.PersistentVolumeClaim: Get \"https://172.18.0.16:6443/api/v1/persistentvolumeclaims?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:56.478889       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PersistentVolume: Get "https://172.18.0.16:6443/api/v1/persistentvolumes?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:56.478961       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PersistentVolume: failed to list *v1.PersistentVolume: Get \"https://172.18.0.16:6443/api/v1/persistentvolumes?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:56.568291       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.PodDisruptionBudget: Get "https://172.18.0.16:6443/apis/policy/v1/poddisruptionbudgets?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:56.568350       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.PodDisruptionBudget: failed to list *v1.PodDisruptionBudget: Get \"https://172.18.0.16:6443/apis/policy/v1/poddisruptionbudgets?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:56.660574       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.Service: Get "https://172.18.0.16:6443/api/v1/services?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:56.660641       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.Service: failed to list *v1.Service: Get \"https://172.18.0.16:6443/api/v1/services?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:57.325020       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.CSIStorageCapacity: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/csistoragecapacities?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:57.325086       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.CSIStorageCapacity: failed to list *v1.CSIStorageCapacity: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/csistoragecapacities?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
W0109 21:49:57.877698       1 reflector.go:561] k8s.io/client-go/informers/factory.go:160: failed to list *v1.StorageClass: Get "https://172.18.0.16:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0": dial tcp 172.18.0.16:6443: connect: connection refused
E0109 21:49:57.877740       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go/informers/factory.go:160: Failed to watch *v1.StorageClass: failed to list *v1.StorageClass: Get \"https://172.18.0.16:6443/apis/storage.k8s.io/v1/storageclasses?limit=500&resourceVersion=0\": dial tcp 172.18.0.16:6443: connect: connection refused" logger="UnhandledError"
I0109 21:50:08.025565       1 shared_informer.go:320] Caches are synced for client-ca::kube-system::extension-apiserver-authentication::client-ca-file
I0109 21:50:09.327271       1 leaderelection.go:254] attempting to acquire leader lease kube-system/kube-scheduler...
I0109 21:50:09.338814       1 leaderelection.go:268] successfully acquired lease kube-system/kube-scheduler
==== END logs for container kube-scheduler of pod kube-system/kube-scheduler-response-1-control-plane ====
